import React from "react";
import Head from "next/head";
import Header from "./Header";

const MainLayout = ({ children }) => {
  return (
    <>
      <Head>
        <title>Ledger</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Header />
      {children}
    </>
  );
};

export default MainLayout;
